### ISSUE TITLE
Support RStudio Server with browser based notifications

### ISSUE THREAD

**Issue by sellorm** [gaborcsardi/notifier#13]
I'm not sure if this is possible, but it would be *really cool* if this also supported RStudio Server using browser based notifications.

**Comment by gaborcsardi** [comment]
Great idea! 

But I have no idea how I could get to the browser from R code..... Maybe Rstudio server has sg.

**Comment by gaborcsardi** [comment]
This is not really possible currently. I can inject JS code through the viewer pane, but that (not surprisingly) interferes with the viewer pane: RStudio switches to the viewer pane when the notification is shown, and the user also needs to close the extra view there.

I can also trick RStudio to believe that the notification is an HTML widget, and then call `window.back()`, so it is removed automatically from the viewer. But it still stays in the viewer history, which is super annoying.

Another alternative is using a Shiny gadget, but that is not ideal, either, because it is modal AFAIK.

I am going to close this for now, because I don't think there will be a good solution anytime soon. We can reopen it in the future, if some support from RStudio becomes available.

**Comment by gaborcsardi** [comment]
Another really hacky idea would be to write a browser extension that we can communicate with from RStudio server in some intricate way, and the extension can create browser notifications...
